Parameters: 
  EnvType: 
    Description: Option to install New Relic Infrastructure.
    Default: apm
    Type: String
    AllowedValues: 
      - apm
      - plusInfra
    ConstraintDescription: must specify apm or +Infra.

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-9c9443e3  #Amazon Linux AMI in Tokyo 
      KeyName: tokyocloudformation
      IamInstanceProfile: 'S3EC2'
      SecurityGroupIds:
        - !Ref myNewSecurityGroup1118
      Tags:
        - Key: Name
          Value: tomcat-linux-newrelic
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            yum update -y
            yum install -y aws-cfn-bootstrap 
            if [ "${EnvType}" = "plusInfra" ]; then
            echo "license_key: 72b4cac51de99980b0c7a5f579f79348a23866c6" | sudo tee -a /etc/newrelic-infra.yml
            cat /etc/os-release
            curl -o /etc/yum.repos.d/newrelic-infra.repo https://download.newrelic.com/infrastructure_agent/linux/yum/el/6/x86_64/newrelic-infra.repo
            yum -q makecache -y --disablerepo='*' --enablerepo='newrelic-infra'
            yum install newrelic-infra -y
            fi
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          apm_monitoring:
            - "configure_cfn"
            - "install_tomcat_nr"
        configure_cfn:
          files:
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.EC2.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2 --configsets wordpress --region ${AWS::Region}
              mode: "000400"
              owner: root
              group: root

            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                interval=1
              mode: '000400'
              owner: root
              group: root

          services:
            sysvinit:
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                  - '/etc/cfn/cfn-hup.conf'
                  - '/etc/cfn/hooks.d/cfn-auto-reloader.conf'
        install_tomcat_nr:
          packages:
            yum:
              tomcat8: []
              tomcat8-webapps: []
              tomcat8-admin-webapps: []
          sources: 
            /usr/share/tomcat8: 's3://tomcat.newrelic.artifacts/newrelic.zip'
            /usr/share/tomcat8: 's3://tomcat.newrelic.artifacts/tomcat8.conf'
          services: 
            sysvinit:
              tomcat:
                enabled: "true"
                ensureRunning: "true"

  myNewSecurityGroup1118:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: tokyoSecurity1118
        GroupDescription: Enable Appropriate ports for tomcat-http and ssh
        VpcId: vpc-1e1df77b

        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '22'
            ToPort: '22'
            CidrIp: 0.0.0.0/0

          - IpProtocol: tcp
            FromPort: '8080'
            ToPort: '8080'
            CidrIp: 0.0.0.0/0
